//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VideoEngagementsModel
{
    public partial class EpisodePlay
    {
        public int EpisodePlayId { get; set; }
        public int PlayTypeId { get; set; }
        public int EpisodeId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public int Duration { get; set; }
        public int Length { get; set; }
        public int AssetId { get; set; }
        public int CategoryId { get; set; }
        public int StartPosition { get; set; }
        public bool IsPreview { get; set; }
        public Nullable<int> StreamType { get; set; }
    }
    
}
