//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VideoEngagementsModel
{
    public partial class YouTubePlay
    {
        public int YouTubePlayId { get; set; }
        public int PlayTypeId { get; set; }
        public string YouTubeId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> Duration { get; set; }
    }
    
}
