//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace EngagementsModel
{
    public partial class ShowReactionSummary
    {
        public int CategoryId { get; set; }
        public int ReactionTypeId { get; set; }
        public int Total { get; set; }
        public int Total7Days { get; set; }
        public int Total30Days { get; set; }
    }
    
}
