//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFCtvAPI_WS_Tester.TFCtvAPI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="TFCtv APISoap", Namespace="http://tfc.tv/", ConfigurationName="TFCtvAPI.TFCtvAPISoap")]
    public interface TFCtvAPISoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tfc.tv/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        // CODEGEN: Generating message contract since message TogglePpcRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tfc.tv/TogglePpc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFCtvAPI_WS_Tester.TFCtvAPI.TogglePpcResponse TogglePpc(TFCtvAPI_WS_Tester.TFCtvAPI.TogglePpcRequest request);
        
        // CODEGEN: Generating message contract since message ReloadWalletViaSmartPitRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tfc.tv/ReloadWalletViaSmartPit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFCtvAPI_WS_Tester.TFCtvAPI.ReloadWalletViaSmartPitResponse ReloadWalletViaSmartPit(TFCtvAPI_WS_Tester.TFCtvAPI.ReloadWalletViaSmartPitRequest request);
        
        // CODEGEN: Generating message contract since message UpdateSmartPitRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tfc.tv/UpdateSmartPit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFCtvAPI_WS_Tester.TFCtvAPI.UpdateSmartPitResponse UpdateSmartPit(TFCtvAPI_WS_Tester.TFCtvAPI.UpdateSmartPitRequest request);
        
        // CODEGEN: Generating message contract since message CreateTFCtvEverywhereEntitlementRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tfc.tv/CreateTFCtvEverywhereEntitlement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFCtvAPI_WS_Tester.TFCtvAPI.CreateTFCtvEverywhereEntitlementResponse CreateTFCtvEverywhereEntitlement(TFCtvAPI_WS_Tester.TFCtvAPI.CreateTFCtvEverywhereEntitlementRequest request);
        
        // CODEGEN: Generating message contract since message UnassociateTVEverywhereRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tfc.tv/UnassociateTVEverywhere", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        TFCtvAPI_WS_Tester.TFCtvAPI.UnassociateTVEverywhereResponse UnassociateTVEverywhere(TFCtvAPI_WS_Tester.TFCtvAPI.UnassociateTVEverywhereRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tfc.tv/")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tfc.tv/")]
    public partial class ReqUnassociateTVEverywhere : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> gomsCustomerIdField;
        
        private System.Nullable<System.DateTime> gomsTransactionDateField;
        
        private System.Nullable<int> gomsTransactionIdField;
        
        private string referenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> GomsCustomerId {
            get {
                return this.gomsCustomerIdField;
            }
            set {
                this.gomsCustomerIdField = value;
                this.RaisePropertyChanged("GomsCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> GomsTransactionDate {
            get {
                return this.gomsTransactionDateField;
            }
            set {
                this.gomsTransactionDateField = value;
                this.RaisePropertyChanged("GomsTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> GomsTransactionId {
            get {
                return this.gomsTransactionIdField;
            }
            set {
                this.gomsTransactionIdField = value;
                this.RaisePropertyChanged("GomsTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tfc.tv/")]
    public partial class ReqCreateTFCtvEverywhereEntitlement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> gomsProductIdField;
        
        private System.Nullable<int> gomsProductQuantityField;
        
        private System.Nullable<int> gomsCustomerIdField;
        
        private string emailAddressField;
        
        private System.Nullable<System.DateTime> gomsTransactionDateField;
        
        private System.Nullable<int> gomsTransactionIdField;
        
        private string referenceField;
        
        private System.Nullable<System.DateTime> gomsTFCEverywhereStartDateField;
        
        private System.Nullable<System.DateTime> gomsTFCEverywhereEndDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> GomsProductId {
            get {
                return this.gomsProductIdField;
            }
            set {
                this.gomsProductIdField = value;
                this.RaisePropertyChanged("GomsProductId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> GomsProductQuantity {
            get {
                return this.gomsProductQuantityField;
            }
            set {
                this.gomsProductQuantityField = value;
                this.RaisePropertyChanged("GomsProductQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<int> GomsCustomerId {
            get {
                return this.gomsCustomerIdField;
            }
            set {
                this.gomsCustomerIdField = value;
                this.RaisePropertyChanged("GomsCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> GomsTransactionDate {
            get {
                return this.gomsTransactionDateField;
            }
            set {
                this.gomsTransactionDateField = value;
                this.RaisePropertyChanged("GomsTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<int> GomsTransactionId {
            get {
                return this.gomsTransactionIdField;
            }
            set {
                this.gomsTransactionIdField = value;
                this.RaisePropertyChanged("GomsTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("Reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> GomsTFCEverywhereStartDate {
            get {
                return this.gomsTFCEverywhereStartDateField;
            }
            set {
                this.gomsTFCEverywhereStartDateField = value;
                this.RaisePropertyChanged("GomsTFCEverywhereStartDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> GomsTFCEverywhereEndDate {
            get {
                return this.gomsTFCEverywhereEndDateField;
            }
            set {
                this.gomsTFCEverywhereEndDateField = value;
                this.RaisePropertyChanged("GomsTFCEverywhereEndDate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tfc.tv/")]
    public partial class ReqUpdateSmartPit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> gomsCustomerIdField;
        
        private string smartPitCardNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> GomsCustomerId {
            get {
                return this.gomsCustomerIdField;
            }
            set {
                this.gomsCustomerIdField = value;
                this.RaisePropertyChanged("GomsCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SmartPitCardNo {
            get {
                return this.smartPitCardNoField;
            }
            set {
                this.smartPitCardNoField = value;
                this.RaisePropertyChanged("SmartPitCardNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tfc.tv/")]
    public partial class ReqReloadWalletViaSmartPit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<int> gomsWalletIdField;
        
        private System.Nullable<int> gomsCustomerIdField;
        
        private System.Nullable<System.DateTime> gomsTransactionDateField;
        
        private System.Nullable<int> gomsTransactionIdField;
        
        private System.Nullable<decimal> amountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<int> GomsWalletId {
            get {
                return this.gomsWalletIdField;
            }
            set {
                this.gomsWalletIdField = value;
                this.RaisePropertyChanged("GomsWalletId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> GomsCustomerId {
            get {
                return this.gomsCustomerIdField;
            }
            set {
                this.gomsCustomerIdField = value;
                this.RaisePropertyChanged("GomsCustomerId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> GomsTransactionDate {
            get {
                return this.gomsTransactionDateField;
            }
            set {
                this.gomsTransactionDateField = value;
                this.RaisePropertyChanged("GomsTransactionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> GomsTransactionId {
            get {
                return this.gomsTransactionIdField;
            }
            set {
                this.gomsTransactionIdField = value;
                this.RaisePropertyChanged("GomsTransactionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
                this.RaisePropertyChanged("Amount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tfc.tv/")]
    public partial class TFCtvResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tfc.tv/")]
    public partial class ReqActivatePpc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ppcStartField;
        
        private string ppcEndField;
        
        private string activatedByField;
        
        private System.Nullable<System.DateTime> activatedOnField;
        
        private System.Nullable<int> statusIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PpcStart {
            get {
                return this.ppcStartField;
            }
            set {
                this.ppcStartField = value;
                this.RaisePropertyChanged("PpcStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PpcEnd {
            get {
                return this.ppcEndField;
            }
            set {
                this.ppcEndField = value;
                this.RaisePropertyChanged("PpcEnd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ActivatedBy {
            get {
                return this.activatedByField;
            }
            set {
                this.activatedByField = value;
                this.RaisePropertyChanged("ActivatedBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> ActivatedOn {
            get {
                return this.activatedOnField;
            }
            set {
                this.activatedOnField = value;
                this.RaisePropertyChanged("ActivatedOn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> StatusId {
            get {
                return this.statusIdField;
            }
            set {
                this.statusIdField = value;
                this.RaisePropertyChanged("StatusId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TogglePpc", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class TogglePpcRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tfc.tv/")]
        public TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.ReqActivatePpc req;
        
        public TogglePpcRequest() {
        }
        
        public TogglePpcRequest(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqActivatePpc req) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TogglePpcResponse", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class TogglePpcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse TogglePpcResult;
        
        public TogglePpcResponse() {
        }
        
        public TogglePpcResponse(TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse TogglePpcResult) {
            this.TogglePpcResult = TogglePpcResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReloadWalletViaSmartPit", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class ReloadWalletViaSmartPitRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tfc.tv/")]
        public TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.ReqReloadWalletViaSmartPit req;
        
        public ReloadWalletViaSmartPitRequest() {
        }
        
        public ReloadWalletViaSmartPitRequest(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqReloadWalletViaSmartPit req) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReloadWalletViaSmartPitResponse", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class ReloadWalletViaSmartPitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse ReloadWalletViaSmartPitResult;
        
        public ReloadWalletViaSmartPitResponse() {
        }
        
        public ReloadWalletViaSmartPitResponse(TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse ReloadWalletViaSmartPitResult) {
            this.ReloadWalletViaSmartPitResult = ReloadWalletViaSmartPitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSmartPit", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class UpdateSmartPitRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tfc.tv/")]
        public TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.ReqUpdateSmartPit req;
        
        public UpdateSmartPitRequest() {
        }
        
        public UpdateSmartPitRequest(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqUpdateSmartPit req) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSmartPitResponse", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class UpdateSmartPitResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse UpdateSmartPitResult;
        
        public UpdateSmartPitResponse() {
        }
        
        public UpdateSmartPitResponse(TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse UpdateSmartPitResult) {
            this.UpdateSmartPitResult = UpdateSmartPitResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTFCtvEverywhereEntitlement", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class CreateTFCtvEverywhereEntitlementRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tfc.tv/")]
        public TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.ReqCreateTFCtvEverywhereEntitlement req;
        
        public CreateTFCtvEverywhereEntitlementRequest() {
        }
        
        public CreateTFCtvEverywhereEntitlementRequest(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqCreateTFCtvEverywhereEntitlement req) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTFCtvEverywhereEntitlementResponse", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class CreateTFCtvEverywhereEntitlementResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse CreateTFCtvEverywhereEntitlementResult;
        
        public CreateTFCtvEverywhereEntitlementResponse() {
        }
        
        public CreateTFCtvEverywhereEntitlementResponse(TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse CreateTFCtvEverywhereEntitlementResult) {
            this.CreateTFCtvEverywhereEntitlementResult = CreateTFCtvEverywhereEntitlementResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnassociateTVEverywhere", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class UnassociateTVEverywhereRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tfc.tv/")]
        public TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.ReqUnassociateTVEverywhere req;
        
        public UnassociateTVEverywhereRequest() {
        }
        
        public UnassociateTVEverywhereRequest(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqUnassociateTVEverywhere req) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UnassociateTVEverywhereResponse", WrapperNamespace="http://tfc.tv/", IsWrapped=true)]
    public partial class UnassociateTVEverywhereResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tfc.tv/", Order=0)]
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse UnassociateTVEverywhereResult;
        
        public UnassociateTVEverywhereResponse() {
        }
        
        public UnassociateTVEverywhereResponse(TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse UnassociateTVEverywhereResult) {
            this.UnassociateTVEverywhereResult = UnassociateTVEverywhereResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TFCtvAPISoapChannel : TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TFCtvAPISoapClient : System.ServiceModel.ClientBase<TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap>, TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap {
        
        public TFCtvAPISoapClient() {
        }
        
        public TFCtvAPISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFCtvAPISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFCtvAPISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFCtvAPISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TFCtvAPI_WS_Tester.TFCtvAPI.TogglePpcResponse TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap.TogglePpc(TFCtvAPI_WS_Tester.TFCtvAPI.TogglePpcRequest request) {
            return base.Channel.TogglePpc(request);
        }
        
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse TogglePpc(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqActivatePpc req) {
            TFCtvAPI_WS_Tester.TFCtvAPI.TogglePpcRequest inValue = new TFCtvAPI_WS_Tester.TFCtvAPI.TogglePpcRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.req = req;
            TFCtvAPI_WS_Tester.TFCtvAPI.TogglePpcResponse retVal = ((TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap)(this)).TogglePpc(inValue);
            return retVal.TogglePpcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TFCtvAPI_WS_Tester.TFCtvAPI.ReloadWalletViaSmartPitResponse TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap.ReloadWalletViaSmartPit(TFCtvAPI_WS_Tester.TFCtvAPI.ReloadWalletViaSmartPitRequest request) {
            return base.Channel.ReloadWalletViaSmartPit(request);
        }
        
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse ReloadWalletViaSmartPit(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqReloadWalletViaSmartPit req) {
            TFCtvAPI_WS_Tester.TFCtvAPI.ReloadWalletViaSmartPitRequest inValue = new TFCtvAPI_WS_Tester.TFCtvAPI.ReloadWalletViaSmartPitRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.req = req;
            TFCtvAPI_WS_Tester.TFCtvAPI.ReloadWalletViaSmartPitResponse retVal = ((TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap)(this)).ReloadWalletViaSmartPit(inValue);
            return retVal.ReloadWalletViaSmartPitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TFCtvAPI_WS_Tester.TFCtvAPI.UpdateSmartPitResponse TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap.UpdateSmartPit(TFCtvAPI_WS_Tester.TFCtvAPI.UpdateSmartPitRequest request) {
            return base.Channel.UpdateSmartPit(request);
        }
        
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse UpdateSmartPit(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqUpdateSmartPit req) {
            TFCtvAPI_WS_Tester.TFCtvAPI.UpdateSmartPitRequest inValue = new TFCtvAPI_WS_Tester.TFCtvAPI.UpdateSmartPitRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.req = req;
            TFCtvAPI_WS_Tester.TFCtvAPI.UpdateSmartPitResponse retVal = ((TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap)(this)).UpdateSmartPit(inValue);
            return retVal.UpdateSmartPitResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TFCtvAPI_WS_Tester.TFCtvAPI.CreateTFCtvEverywhereEntitlementResponse TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap.CreateTFCtvEverywhereEntitlement(TFCtvAPI_WS_Tester.TFCtvAPI.CreateTFCtvEverywhereEntitlementRequest request) {
            return base.Channel.CreateTFCtvEverywhereEntitlement(request);
        }
        
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse CreateTFCtvEverywhereEntitlement(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqCreateTFCtvEverywhereEntitlement req) {
            TFCtvAPI_WS_Tester.TFCtvAPI.CreateTFCtvEverywhereEntitlementRequest inValue = new TFCtvAPI_WS_Tester.TFCtvAPI.CreateTFCtvEverywhereEntitlementRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.req = req;
            TFCtvAPI_WS_Tester.TFCtvAPI.CreateTFCtvEverywhereEntitlementResponse retVal = ((TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap)(this)).CreateTFCtvEverywhereEntitlement(inValue);
            return retVal.CreateTFCtvEverywhereEntitlementResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TFCtvAPI_WS_Tester.TFCtvAPI.UnassociateTVEverywhereResponse TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap.UnassociateTVEverywhere(TFCtvAPI_WS_Tester.TFCtvAPI.UnassociateTVEverywhereRequest request) {
            return base.Channel.UnassociateTVEverywhere(request);
        }
        
        public TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvResponse UnassociateTVEverywhere(TFCtvAPI_WS_Tester.TFCtvAPI.AuthenticationHeader AuthenticationHeader, TFCtvAPI_WS_Tester.TFCtvAPI.ReqUnassociateTVEverywhere req) {
            TFCtvAPI_WS_Tester.TFCtvAPI.UnassociateTVEverywhereRequest inValue = new TFCtvAPI_WS_Tester.TFCtvAPI.UnassociateTVEverywhereRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.req = req;
            TFCtvAPI_WS_Tester.TFCtvAPI.UnassociateTVEverywhereResponse retVal = ((TFCtvAPI_WS_Tester.TFCtvAPI.TFCtvAPISoap)(this)).UnassociateTVEverywhere(inValue);
            return retVal.UnassociateTVEverywhereResult;
        }
    }
}
