//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetCdn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetCdn()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int AssetId { get; set; }
        public int CdnId { get; set; }
        public string CdnReference { get; set; }
        public Nullable<int> Priority { get; set; }
        public string CdnContentId { get; set; }
        public Nullable<long> Filesize { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual Asset Asset { get; set; }
        public virtual CDN CDN { get; set; }
    }
}
