//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asset()
        {
            this.AssetCdns = new HashSet<AssetCdn>();
            this.EpisodeFreeAssets = new HashSet<EpisodeFreeAsset>();
            this.EpisodePaidAssets = new HashSet<EpisodePremiumAsset>();
            this.EpisodePreviewAssets = new HashSet<EpisodePreviewAsset>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int AssetId { get; set; }
        public string Filename { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.TimeSpan> Gap1 { get; set; }
        public Nullable<System.TimeSpan> Gap2 { get; set; }
        public Nullable<System.TimeSpan> Gap3 { get; set; }
        public Nullable<System.TimeSpan> Gap4 { get; set; }
        public Nullable<System.TimeSpan> Gap5 { get; set; }
        public Nullable<System.TimeSpan> Gap6 { get; set; }
        public Nullable<System.TimeSpan> Gap7 { get; set; }
        public Nullable<System.TimeSpan> Gap8 { get; set; }
        public Nullable<System.TimeSpan> Gap9 { get; set; }
        public Nullable<System.TimeSpan> Gap10 { get; set; }
        public Nullable<System.TimeSpan> Gap11 { get; set; }
        public Nullable<System.TimeSpan> Gap12 { get; set; }
        public Nullable<System.TimeSpan> Gap13 { get; set; }
        public Nullable<System.TimeSpan> Gap14 { get; set; }
        public Nullable<System.TimeSpan> Gap15 { get; set; }
        public int TotalGaps { get; set; }
        public Nullable<System.TimeSpan> SnippetStart { get; set; }
        public Nullable<System.TimeSpan> SnippetEnd { get; set; }
        public string SnippetCopy { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetCdn> AssetCdns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpisodeFreeAsset> EpisodeFreeAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpisodePremiumAsset> EpisodePaidAssets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpisodePreviewAsset> EpisodePreviewAssets { get; set; }
    }
}
