//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BetaTester
    {
        public int TesterId { get; set; }
        public string EMailAddress { get; set; }
        public System.Guid InvitationKey { get; set; }
        public Nullable<System.Guid> InvitedBy { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> DateClaimed { get; set; }
        public string IpAddress { get; set; }
    }
}
