//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarouselSlide
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarouselSlide()
        {
            this.Carousels = new HashSet<Carousel>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int CarouselSlideId { get; set; }
        public string Name { get; set; }
        public string BannerImageUrl { get; set; }
        public string ThumbnailUrl { get; set; }
        public string Header { get; set; }
        public string Blurb { get; set; }
        public string ButtonLabel { get; set; }
        public string TargetUrl { get; set; }
        public byte StatusId { get; set; }
        public int MobileStatusId { get; set; }
        public int IptvStatusId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carousel> Carousels { get; set; }
        public virtual Status Status { get; set; }
    }
}
