//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Carousel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carousel()
        {
            this.CarouselSlides = new HashSet<CarouselSlide>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int CarouselId { get; set; }
        public string Name { get; set; }
        public int Transition { get; set; }
        public int Drop { get; set; }
        public int OfferingId { get; set; }
        public byte StatusId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarouselSlide> CarouselSlides { get; set; }
        public virtual Offering Offering { get; set; }
        public virtual Status Status { get; set; }
    }
}
