//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class CategoryCountryRestriction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryCountryRestriction()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int CategoryRestrictionId { get; set; }
        public string CountryCode { get; set; }
        public int CategoryId { get; set; }
        public byte StatusId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
