//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class CategoryClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoryClass()
        {
            this.CategoryClassParentCategories = new HashSet<CategoryRelationship>();
            this.Carousels = new HashSet<CategoryCarousel>();
            this.CategoryClassSubCategories = new HashSet<CategoryRelationship>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string SplashImageSmall { get; set; }
        public string SplashImageMedium { get; set; }
        public string BackgroundImage { get; set; }
        public byte StatusId { get; set; }
        public string ImageTitle { get; set; }
        public string ImageBanner { get; set; }
        public string ImagePoster { get; set; }
        public string ImageMobileIcon { get; set; }
        public string ImageMobileLandscape { get; set; }
        public string ImageTitleBanner { get; set; }
        public string ThemeCss { get; set; }
        public string Blurb { get; set; }
        public string ImageSocialNetwork { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryRelationship> CategoryClassParentCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryCarousel> Carousels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryRelationship> CategoryClassSubCategories { get; set; }
    }
}
