//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CDN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CDN()
        {
            this.AssetCdns = new HashSet<AssetCdn>();
            this.ChannelCdns = new HashSet<ChannelCdn>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int CdnId { get; set; }
        public string CdnName { get; set; }
        public string Description { get; set; }
        public bool Deleted { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssetCdn> AssetCdns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelCdn> ChannelCdns { get; set; }
    }
}
