//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Celebrity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Celebrity()
        {
            this.ShowCelebrityRoles = new HashSet<ShowCelebrityRole>();
            this.EpisodeCelebrityRoles = new HashSet<EpisodeCelebrityRole>();
            this.CelebrityRoles = new HashSet<CelebrityRole>();
            this.CelebrityFeatureItems = new HashSet<CelebrityFeatureItem>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int CelebrityId { get; set; }
        public bool IsIndividual { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
        public string Birthplace { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Birthday { get; set; }
        public string ZodiacSign { get; set; }
        public string ChineseYear { get; set; }
        public byte StatusId { get; set; }
        public string ImageUrl { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowCelebrityRole> ShowCelebrityRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpisodeCelebrityRole> EpisodeCelebrityRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CelebrityRole> CelebrityRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CelebrityFeatureItem> CelebrityFeatureItems { get; set; }
        public virtual Status Status { get; set; }
    }
}
