//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class CelebrityRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CelebrityRole()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int CelebirtyRoleId { get; set; }
        public int CelebrityId { get; set; }
        public int RoleTypeId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual RoleType RoleType { get; set; }
        public virtual Celebrity thisCelebrity { get; set; }
    }
}
