//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Channel()
        {
            this.Packages = new HashSet<PackageChannel>();
            this.ProgramSchedules = new HashSet<ProgramSchedule>();
            this.ChannelFeatureItems = new HashSet<ChannelFeatureItem>();
            this.OnlineAllowedCountries = new HashSet<ChannelOnlineAllowedCountry>();
            this.OnlineBlockedCountries = new HashSet<ChannelOnlineBlockedCountry>();
            this.MobileAllowedCountries = new HashSet<ChannelMobileAllowedCountry>();
            this.MobileBlockedCountries = new HashSet<ChannelMobileBlockedCountry>();
            this.IptvAllowedCountries = new HashSet<ChannelIptvAllowedCountry>();
            this.IptvBlockedCountries = new HashSet<ChannelIptvBlockedCountry>();
            this.ChannelCdns = new HashSet<ChannelCdn>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int ChannelId { get; set; }
        public string ChannelName { get; set; }
        public string Description { get; set; }
        public string VideoStream { get; set; }
        public bool Deleted { get; set; }
        public string SplashImageSmall { get; set; }
        public string SplashImageMedium { get; set; }
        public string BackgroundImage { get; set; }
        public byte StatusId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public byte OnlineStatusId { get; set; }
        public Nullable<System.DateTime> OnlineStartDate { get; set; }
        public Nullable<System.DateTime> OnlineEndDate { get; set; }
        public byte MobileStatusId { get; set; }
        public Nullable<System.DateTime> MobileStartDate { get; set; }
        public Nullable<System.DateTime> MobileEndDate { get; set; }
        public string ImageTitle { get; set; }
        public string ImageBanner { get; set; }
        public string ImagePoster { get; set; }
        public string ImageMobileIcon { get; set; }
        public string ImageMobileLandscape { get; set; }
        public string ImageTitleBanner { get; set; }
        public string Blurb { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageChannel> Packages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramSchedule> ProgramSchedules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelFeatureItem> ChannelFeatureItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelOnlineAllowedCountry> OnlineAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelOnlineBlockedCountry> OnlineBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelMobileAllowedCountry> MobileAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelMobileBlockedCountry> MobileBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelIptvAllowedCountry> IptvAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelIptvBlockedCountry> IptvBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChannelCdn> ChannelCdns { get; set; }
    }
}
