//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.CategoryOnlineAllowedCountries = new HashSet<CategoryOnlineAllowedCountry>();
            this.CategoryOnlineBlockedCountries = new HashSet<CategoryOnlineBlockedCountry>();
            this.CategoryMobileAllowedCountries = new HashSet<CategoryMobileAllowedCountry>();
            this.CategoryMobileBlockedCountries = new HashSet<CategoryMobileBlockedCountry>();
            this.CategoryIptvAllowedCountries = new HashSet<CategoryIptvAllowedCountry>();
            this.CategoryIptvBlockedCountries = new HashSet<CategoryIptvBlockedCountry>();
            this.Users = new HashSet<User>();
            this.StoreFronts = new HashSet<StoreFront>();
            this.States = new HashSet<State>();
            this.MopayButtons = new HashSet<MopayButton>();
            this.CountryBitrates = new HashSet<CountryBitrate>();
        }
    
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> GMT { get; set; }
        public string CurrencyCode { get; set; }
        public string GomsSubsidiaryName { get; set; }
        public Nullable<int> GomsCountryId { get; set; }
        public Nullable<int> GomsSubsidiaryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOnlineAllowedCountry> CategoryOnlineAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOnlineBlockedCountry> CategoryOnlineBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryMobileAllowedCountry> CategoryMobileAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryMobileBlockedCountry> CategoryMobileBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryIptvAllowedCountry> CategoryIptvAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryIptvBlockedCountry> CategoryIptvBlockedCountries { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        public virtual GomsSubsidiary GomsSubsidiary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StoreFront> StoreFronts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State> States { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MopayButton> MopayButtons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryBitrate> CountryBitrates { get; set; }
    }
}
