//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryBitrate
    {
        public int CountryBitrateId { get; set; }
        public Nullable<int> LowerLimit { get; set; }
        public Nullable<int> UpperLimit { get; set; }
        public Nullable<int> Platform { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> ProgressiveHDBitrate { get; set; }
        public Nullable<int> ProgressiveHighBitrate { get; set; }
        public Nullable<int> ProgressiveLowBitrate { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
