//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditCard
    {
        public int CCId { get; set; }
        public string CreditCardHash { get; set; }
        public string LastDigits { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public System.Guid UserId { get; set; }
        public int OfferingId { get; set; }
        public int PaymentMethodId { get; set; }
        public string CardType { get; set; }
    
        public virtual User User { get; set; }
        public virtual Offering Offering { get; set; }
        public virtual GomsPaymentMethod GomsPaymentMethod { get; set; }
    }
}
