//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitlementRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntitlementRequest()
        {
            this.PurchaseItems = new HashSet<PurchaseItem>();
            this.Entitlements = new HashSet<Entitlement>();
        }
    
        public int EntitlementRequestId { get; set; }
        public System.Guid UserId { get; set; }
        public int ProductId { get; set; }
        public string Source { get; set; }
        public string ReferenceId { get; set; }
        public System.DateTime DateRequested { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItem> PurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entitlement> Entitlements { get; set; }
    }
}
