//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Entitlement
    {
        public int EntitlementId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime EndDate { get; set; }
        public int OfferingId { get; set; }
        public Nullable<int> LatestEntitlementRequestId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Offering Offering { get; set; }
        public virtual EntitlementRequest LatestEntitlementRequest { get; set; }
    }
}
