//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class EpisodeAsset
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EpisodeAsset()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int EpisodeId { get; set; }
        public int AssetId { get; set; }
        public Nullable<int> Priority { get; set; }
        public bool Preview { get; set; }
        public int EpisodeAssetId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual Episode ParentEpisode { get; set; }
    }
}
