//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpisodeCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EpisodeCategory()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int EpisodeId { get; set; }
        public int CategoryId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual Episode Episode { get; set; }
        public virtual Show Show { get; set; }
    }
}
