//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Feature()
        {
            this.FeatureItems = new HashSet<FeatureItem>();
            this.AuditTrail = new AuditTrail();
        }
    
        public int FeatureId { get; set; }
        public int OfferingId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public byte StatusId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureItem> FeatureItems { get; set; }
        public virtual Offering Offering { get; set; }
        public virtual Status Status { get; set; }
    }
}
