//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forex
    {
        public string BaseCurrencyCode { get; set; }
        public string TargetCurrencyCode { get; set; }
        public double ExchangeRate { get; set; }
        public Nullable<System.Guid> UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Currency BaseCurrency { get; set; }
        public virtual Currency TargetCurrency { get; set; }
    }
}
