//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    
    public partial class ImageAssets
    {
        public string ImageSmall { get; set; }
        public string ImageMedium { get; set; }
        public string ImageLarge { get; set; }
        public string ImageBackground { get; set; }
        public string ImageHeader { get; set; }
        public string ImageMobile { get; set; }
        public string ImagePlaylist { get; set; }
        public string ImageVideo { get; set; }
    }
}
