//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MopayTransactionRequest
    {
        public string GUID { get; set; }
        public string ReferenceId { get; set; }
        public string Currency { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public int NumberOfAttempts { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorMessage { get; set; }
        public string StatusId { get; set; }
        public System.Guid UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
