//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MopayButton
    {
        public string ButtonId { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public int StatusId { get; set; }
        public string CountryCode { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
