//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Ppc
    {
        public int PpcId { get; set; }
        public string SerialNumber { get; set; }
        public string Pin { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public decimal Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> UsedDate { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public int PpcProductId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> ActivatedOn { get; set; }
        public string ActivatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual PpcType PpcType { get; set; }
    }
}
