//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class PpcType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PpcType()
        {
            this.Ppcs = new HashSet<Ppc>();
            this.PpcTypeCurrencies = new HashSet<PpcTypeCurrency>();
        }
    
        public int PpcProductId { get; set; }
        public string PpcProductCode { get; set; }
        public string Currency { get; set; }
        public decimal Amount { get; set; }
        public string Description { get; set; }
        public Nullable<int> GomsSubsidiaryId { get; set; }
        public Nullable<int> GomsPpcTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ppc> Ppcs { get; set; }
        public virtual GomsSubsidiary GomsSubsidiary { get; set; }
        public virtual Currency CurrencyReference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PpcTypeCurrency> PpcTypeCurrencies { get; set; }
    }
}
