//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductPrice()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int ProductId { get; set; }
        public decimal Amount { get; set; }
        public string CurrencyCode { get; set; }
        public string PayPalButtonId { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal DiscountPercentage { get; set; }
        public string DiscountCopy { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Currency Currency { get; set; }
    }
}
