//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductGroup()
        {
            this.ProductGroupUpgrades = new HashSet<ProductGroupUpgrade>();
            this.UpgradeToProductGroupUpgrades = new HashSet<ProductGroupUpgrade>();
            this.SubscriptionProducts = new HashSet<SubscriptionProduct>();
        }
    
        public int ProductGroupId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int OfferingId { get; set; }
        public Nullable<int> ProductSubscriptionTypeId { get; set; }
        public Nullable<int> DefaultProductId { get; set; }
        public string Blurb { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGroupUpgrade> ProductGroupUpgrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductGroupUpgrade> UpgradeToProductGroupUpgrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubscriptionProduct> SubscriptionProducts { get; set; }
        public virtual Offering Offering { get; set; }
    }
}
