//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductPackage()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int ProductId { get; set; }
        public int PackageId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual PackageType Package { get; set; }
        public virtual PackageSubscriptionProduct Product { get; set; }
    }
}
