//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringBilling
    {
        public int RecurringBillingId { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<System.DateTime> NextRun { get; set; }
        public System.Guid UserId { get; set; }
        public int ProductId { get; set; }
        public int OfferingId { get; set; }
        public int PackageId { get; set; }
        public Nullable<System.DateTime> LastSentEmail { get; set; }
        public string GomsRemarks { get; set; }
        public Nullable<int> NumberOfAttempts { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
        public virtual Offering Offering { get; set; }
        public virtual Package Package { get; set; }
    }
}
