//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Show : CategoryClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Show()
        {
            this.CelebrityRoles = new HashSet<ShowCelebrityRole>();
            this.Products = new HashSet<ProductShow>();
            this.OnlineAllowedCountries = new HashSet<CategoryOnlineAllowedCountry>();
            this.OnlineBlockedCountries = new HashSet<CategoryOnlineBlockedCountry>();
            this.MobileAllowedCountries = new HashSet<CategoryMobileAllowedCountry>();
            this.MobileBlockedCountries = new HashSet<CategoryMobileBlockedCountry>();
            this.IptvAllowedCountries = new HashSet<CategoryIptvAllowedCountry>();
            this.IptvBlockedCountries = new HashSet<CategoryIptvBlockedCountry>();
            this.Episodes = new HashSet<EpisodeCategory>();
            this.ShowEntitlements = new HashSet<ShowEntitlement>();
            this.ParentCategories = new HashSet<Category>();
            this.ShowFeatureItems = new HashSet<ShowFeatureItem>();
            this.CategoryRestrictions = new HashSet<CategoryRestrictions>();
        }
    
        public Nullable<bool> PayPerView { get; set; }
        public Nullable<bool> PlayLatestEpisode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowCelebrityRole> CelebrityRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductShow> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOnlineAllowedCountry> OnlineAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryOnlineBlockedCountry> OnlineBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryMobileAllowedCountry> MobileAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryMobileBlockedCountry> MobileBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryIptvAllowedCountry> IptvAllowedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryIptvBlockedCountry> IptvBlockedCountries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpisodeCategory> Episodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowEntitlement> ShowEntitlements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> ParentCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowFeatureItem> ShowFeatureItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryRestrictions> CategoryRestrictions { get; set; }
    }
}
