//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreFront
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StoreFront()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int StoreFrontId { get; set; }
        public int OfferingId { get; set; }
        public string BusinessName { get; set; }
        public string ContactPerson { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string CountryCode { get; set; }
        public string BusinessPhone { get; set; }
        public string EMailAddress { get; set; }
        public string WebSiteUrl { get; set; }
        public string MobilePhone { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public int StatusId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Offering Offering { get; set; }
    }
}
