//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Transaction
    {
        public int TransactionId { get; set; }
        public System.Guid UserId { get; set; }
        public string Currency { get; set; }
        public decimal Amount { get; set; }
        public string Reference { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> GomsTransactionId { get; set; }
        public Nullable<System.DateTime> GomsTransactionDate { get; set; }
        public int OfferingId { get; set; }
        public int StatusId { get; set; }
        public string GomsRemarks { get; set; }
        public Nullable<int> NumberOfAttempts { get; set; }
    
        public virtual User User { get; set; }
        public virtual Offering Offering { get; set; }
    }
}
