//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpgradeTransaction : Transaction
    {
        public int OriginalProductId { get; set; }
        public Nullable<System.DateTime> OriginalExpirationDate { get; set; }
        public int NewProductId { get; set; }
        public Nullable<System.DateTime> NewExpirationDate { get; set; }
    
        public virtual SubscriptionProduct OriginalSubscriptionProduct { get; set; }
        public virtual SubscriptionProduct NewSubscriptionProduct { get; set; }
    }
}
