//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPromo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPromo()
        {
            this.AuditTrail = new AuditTrail();
        }
    
        public int PromoId { get; set; }
        public System.Guid UserId { get; set; }
    
        public AuditTrail AuditTrail { get; set; }
    
        public virtual User User { get; set; }
        public virtual Promo Promo { get; set; }
    }
}
