//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPTV2_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.EntitlementRequests = new HashSet<EntitlementRequest>();
            this.Entitlements = new HashSet<Entitlement>();
            this.UserWallets = new HashSet<UserWallet>();
            this.Transactions = new HashSet<Transaction>();
            this.Purchases = new HashSet<Purchase>();
            this.PurchaseItems = new HashSet<PurchaseItem>();
            this.Ppcs = new HashSet<Ppc>();
            this.EpisodeEntitlements = new HashSet<EpisodeEntitlement>();
            this.ShowEntitlements = new HashSet<ShowEntitlement>();
            this.PackageEntitlements = new HashSet<PackageEntitlement>();
            this.RecurringBillings = new HashSet<RecurringBilling>();
            this.CreditCards = new HashSet<CreditCard>();
            this.PaypalIPNLogs = new HashSet<PaypalIPNLog>();
            this.UserPromos = new HashSet<UserPromo>();
            this.MopayTransactionRequests = new HashSet<MopayTransactionRequest>();
        }
    
        public System.Guid UserId { get; set; }
        public string EMail { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string GigyaUID { get; set; }
        public string CountryCode { get; set; }
        public Nullable<int> GomsCustomerId { get; set; }
        public Nullable<int> GomsServiceId { get; set; }
        public Nullable<int> GomsWalletId { get; set; }
        public Nullable<int> GomsSubsidiaryId { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int InternalUserId { get; set; }
        public string RegistrationIp { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<System.DateTime> DateVerified { get; set; }
        public Nullable<System.Guid> ActivationKey { get; set; }
        public string SmartPitId { get; set; }
        public Nullable<System.DateTime> SmartPitRegistrationDate { get; set; }
        public string TfcNowUserName { get; set; }
        public Nullable<bool> IsTVEverywhere { get; set; }
        public Nullable<bool> IsTVERegistrant { get; set; }
        public string SessionId { get; set; }
        public Nullable<System.DateTime> SessionLoggedDate { get; set; }
        public string RegistrationCookie { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntitlementRequest> EntitlementRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entitlement> Entitlements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserWallet> UserWallets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItem> PurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ppc> Ppcs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpisodeEntitlement> EpisodeEntitlements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowEntitlement> ShowEntitlements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageEntitlement> PackageEntitlements { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecurringBilling> RecurringBillings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaypalIPNLog> PaypalIPNLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPromo> UserPromos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MopayTransactionRequest> MopayTransactionRequests { get; set; }
        public virtual ITEDetail ITEDetail { get; set; }
    }
}
