//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TFCTV {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SNSTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SNSTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TFCTV.SNSTemplates", typeof(SNSTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has posted something new about {0}: .
        /// </summary>
        internal static string about_description_internal {
            get {
                return ResourceManager.GetString("about_description_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        internal static string actionlink_text {
            get {
                return ResourceManager.GetString("actionlink_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string actionlink_text_generic {
            get {
                return ResourceManager.GetString("actionlink_text_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /User/Register.
        /// </summary>
        internal static string register_actionlink_href {
            get {
                return ResourceManager.GetString("register_actionlink_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register here!.
        /// </summary>
        internal static string register_actionlink_text {
            get {
                return ResourceManager.GetString("register_actionlink_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has just joined the digital tambayan of the global Pinoy!.
        /// </summary>
        internal static string register_description {
            get {
                return ResourceManager.GetString("register_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /User/Register.
        /// </summary>
        internal static string register_linkback {
            get {
                return ResourceManager.GetString("register_linkback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /User/Register.
        /// </summary>
        internal static string register_mediaitem_href {
            get {
                return ResourceManager.GetString("register_mediaitem_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/actions/small_tfctv_dark.png.
        /// </summary>
        internal static string register_mediaitem_src {
            get {
                return ResourceManager.GetString("register_mediaitem_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string register_mediaitem_type {
            get {
                return ResourceManager.GetString("register_mediaitem_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string register_subtitle {
            get {
                return ResourceManager.GetString("register_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now on TFC.tv.
        /// </summary>
        internal static string register_title {
            get {
                return ResourceManager.GetString("register_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is now part of TFC.tv.
        /// </summary>
        internal static string register_usermessage {
            get {
                return ResourceManager.GetString("register_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string rgift_actionlink_href {
            get {
                return ResourceManager.GetString("rgift_actionlink_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feel the love on TFC.tv by receiving products as gifts from users worldwide..
        /// </summary>
        internal static string rgift_description {
            get {
                return ResourceManager.GetString("rgift_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string rgift_description_internal {
            get {
                return ResourceManager.GetString("rgift_description_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string rgift_linkback {
            get {
                return ResourceManager.GetString("rgift_linkback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string rgift_mediaitem_href {
            get {
                return ResourceManager.GetString("rgift_mediaitem_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/actions/gift-icon.png.
        /// </summary>
        internal static string rgift_mediaitem_src {
            get {
                return ResourceManager.GetString("rgift_mediaitem_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/actions/gift-icon-internal.png.
        /// </summary>
        internal static string rgift_mediaitem_src_internal {
            get {
                return ResourceManager.GetString("rgift_mediaitem_src_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string rgift_mediaitem_type {
            get {
                return ResourceManager.GetString("rgift_mediaitem_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string rgift_subtitle {
            get {
                return ResourceManager.GetString("rgift_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Gifts on TFC.tv.
        /// </summary>
        internal static string rgift_title {
            get {
                return ResourceManager.GetString("rgift_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has received a {0} gift from &lt;a href=&quot;/Profile/{1}&quot;&gt;{2}&lt;/a&gt;.
        /// </summary>
        internal static string rgift_usermessage {
            get {
                return ResourceManager.GetString("rgift_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has received a {0} gift from {1}.
        /// </summary>
        internal static string rgift_usermessage_external {
            get {
                return ResourceManager.GetString("rgift_usermessage_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sgift_actionlink_href {
            get {
                return ResourceManager.GetString("sgift_actionlink_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share the love on TFC.tv by purchasing products as gifts to users worldwide..
        /// </summary>
        internal static string sgift_description {
            get {
                return ResourceManager.GetString("sgift_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sgift_description_internal {
            get {
                return ResourceManager.GetString("sgift_description_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string sgift_linkback {
            get {
                return ResourceManager.GetString("sgift_linkback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string sgift_mediaitem_href {
            get {
                return ResourceManager.GetString("sgift_mediaitem_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/actions/gift-icon.png.
        /// </summary>
        internal static string sgift_mediaitem_src {
            get {
                return ResourceManager.GetString("sgift_mediaitem_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/actions/gift-icon-internal.png.
        /// </summary>
        internal static string sgift_mediaitem_src_internal {
            get {
                return ResourceManager.GetString("sgift_mediaitem_src_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string sgift_mediaitem_type {
            get {
                return ResourceManager.GetString("sgift_mediaitem_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string sgift_subtitle {
            get {
                return ResourceManager.GetString("sgift_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Gifts on TFC.tv.
        /// </summary>
        internal static string sgift_title {
            get {
                return ResourceManager.GetString("sgift_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has sent a {0} gift to &lt;a href=&quot;/Profile/{1}&quot;&gt;{2}&lt;/a&gt;.
        /// </summary>
        internal static string sgift_usermessage {
            get {
                return ResourceManager.GetString("sgift_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has sent a {0} gift to {1}.
        /// </summary>
        internal static string sgift_usermessage_external {
            get {
                return ResourceManager.GetString("sgift_usermessage_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string status_actionlink_href {
            get {
                return ResourceManager.GetString("status_actionlink_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string status_description_external {
            get {
                return ResourceManager.GetString("status_description_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to says {0}.
        /// </summary>
        internal static string status_description_internal {
            get {
                return ResourceManager.GetString("status_description_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string status_linkback {
            get {
                return ResourceManager.GetString("status_linkback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string status_mediaitem_href {
            get {
                return ResourceManager.GetString("status_mediaitem_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/logo/small_tfctv_dark.png.
        /// </summary>
        internal static string status_mediaitem_src {
            get {
                return ResourceManager.GetString("status_mediaitem_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string status_mediaitem_type {
            get {
                return ResourceManager.GetString("status_mediaitem_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string status_subtitle {
            get {
                return ResourceManager.GetString("status_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say it on TFC.tv.
        /// </summary>
        internal static string status_title_external {
            get {
                return ResourceManager.GetString("status_title_external", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Profile page.
        /// </summary>
        internal static string status_title_internal {
            get {
                return ResourceManager.GetString("status_title_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has updated {0} status on TFC.tv.
        /// </summary>
        internal static string status_usermessage {
            get {
                return ResourceManager.GetString("status_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://tfc.tv.
        /// </summary>
        internal static string subtitle_generic {
            get {
                return ResourceManager.GetString("subtitle_generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Episode/Details/{0}.
        /// </summary>
        internal static string watch_actionlink_href {
            get {
                return ResourceManager.GetString("watch_actionlink_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy your favorite TFC shows only from the largest and official source on the web..
        /// </summary>
        internal static string watch_description {
            get {
                return ResourceManager.GetString("watch_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Episode/Details/{0}.
        /// </summary>
        internal static string watch_linkback {
            get {
                return ResourceManager.GetString("watch_linkback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Episode/Details/{0}.
        /// </summary>
        internal static string watch_mediaitem_href {
            get {
                return ResourceManager.GetString("watch_mediaitem_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}/{2}.
        /// </summary>
        internal static string watch_mediaitem_src {
            get {
                return ResourceManager.GetString("watch_mediaitem_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string watch_mediaitem_type {
            get {
                return ResourceManager.GetString("watch_mediaitem_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enjoy your favorite TFC movies only from the largest and official source on the web..
        /// </summary>
        internal static string watch_movie_description {
            get {
                return ResourceManager.GetString("watch_movie_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has watched a preview of {0}.
        /// </summary>
        internal static string watch_movie_preview_usermessage {
            get {
                return ResourceManager.GetString("watch_movie_preview_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinoy Movies on TFC.tv.
        /// </summary>
        internal static string watch_movie_title {
            get {
                return ResourceManager.GetString("watch_movie_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has watched the movie {0}.
        /// </summary>
        internal static string watch_movie_usermessage {
            get {
                return ResourceManager.GetString("watch_movie_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has watched a preview of {0}.
        /// </summary>
        internal static string watch_preview_usermessage {
            get {
                return ResourceManager.GetString("watch_preview_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Episode/Details/{0}.
        /// </summary>
        internal static string watch_subtitle {
            get {
                return ResourceManager.GetString("watch_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinoy TV Shows on TFC.tv.
        /// </summary>
        internal static string watch_title {
            get {
                return ResourceManager.GetString("watch_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has watched an episode of {0}.
        /// </summary>
        internal static string watch_usermessage {
            get {
                return ResourceManager.GetString("watch_usermessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}#Wishlist.
        /// </summary>
        internal static string wishlist_actionlink_href {
            get {
                return ResourceManager.GetString("wishlist_actionlink_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build your own wishlist and share with other TFC.tv users the products that you want..
        /// </summary>
        internal static string wishlist_description {
            get {
                return ResourceManager.GetString("wishlist_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string wishlist_description_internal {
            get {
                return ResourceManager.GetString("wishlist_description_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}#Wishlist.
        /// </summary>
        internal static string wishlist_linkback {
            get {
                return ResourceManager.GetString("wishlist_linkback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}#Wishlist.
        /// </summary>
        internal static string wishlist_mediaitem_href {
            get {
                return ResourceManager.GetString("wishlist_mediaitem_href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/actions/wish-icon.png.
        /// </summary>
        internal static string wishlist_mediaitem_src {
            get {
                return ResourceManager.GetString("wishlist_mediaitem_src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /content/images/actions/wish-icon-internal.png.
        /// </summary>
        internal static string wishlist_mediaitem_src_internal {
            get {
                return ResourceManager.GetString("wishlist_mediaitem_src_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string wishlist_mediaitem_type {
            get {
                return ResourceManager.GetString("wishlist_mediaitem_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Profile/{0}.
        /// </summary>
        internal static string wishlist_subtitle {
            get {
                return ResourceManager.GetString("wishlist_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Wishlist on TFC.tv.
        /// </summary>
        internal static string wishlist_title {
            get {
                return ResourceManager.GetString("wishlist_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has added {0} to {1} wishlist.
        /// </summary>
        internal static string wishlist_usermessage {
            get {
                return ResourceManager.GetString("wishlist_usermessage", resourceCulture);
            }
        }
    }
}
